#include "/Engine/Public/Platform.ush"

StructuredBuffer<double4> InputVectors;
RWStructuredBuffer<double4> OutputVectors : register(u0);

int NumParticles;
float SpawnLength;

[numthreads(THREADS_X, THREADS_Y, THREADS_Z)]
void InitializeParticle(
    uint3 DispatchThreadId : SV_DispatchThreadID
)
{
    uint ThreadId = DispatchThreadId.x;
    
    if (ThreadId >= NumParticles)
    {
        return;
    }
    OutputVectors[0] = double4(1.0, 1.0, 1.0, 0.0);
}